apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: author-testing-http-abort
spec:
  hosts:
    - authors
  http:
    - fault:
        abort:
          httpStatus: 500
          percent: 100
      route:
        - destination:
            host: authors
            subset: v1
    - route:
        - destination:
            host: authors
            subset: v2
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: authors
spec:
  host: authors
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2